general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    #deployTool: 'mtaDeployPlugin'
    deployTool: 'cf_native'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      org: 'A-Team_ml'
      space: 'ml'
      credentialsId: 'CF_CREDENTIALSID'
      dockerWorkspace: '/home/jenkins/piper'
